version: 2.1

jobs:
  base-workflow:
    docker:
      - image: cimg/node:20.7
    steps:
      - checkout
      - run:
          name: "Install pnpm package manager"
          command: |
            sudo corepack enable
            sudo corepack prepare pnpm@latest-8 --activate
            pnpm install
      - save_cache:
          name: Save pnpm Package cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules

  lint:
    docker:
      - image: cimg/node:20.7
    steps:
      - run: node --version
      - run: pnpm --version
      - checkout
      - restore_cache:
          name: Restore pnpm Package cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: "Lint monorepo"
          command: pnpm lint
  build:
    docker:
      - image: cimg/node:20.7
    steps:
      - checkout
      - run: node --version
      - run: whoami
      - run:
          name: Install pnpm package manager
          command: |
            sudo corepack enable
            sudo corepack prepare pnpm@latest-8 --activate
      - restore_cache:
          name: Restore pnpm Package cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install Dependencies
          command: pnpm install
      - run:
          name: Build monorepo
          command: pnpm build
      - save_cache:
          name: Save build cache
          key: build-cache-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - '.next/**'
            - '!.next/cache/**'

workflows:

  lint-build:
    jobs:
      - base-workflow
      - lint:
          requires:
            - base-workflow
      - build:
          requires:
            - base-workflow
