version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/node:20.7
    steps:
      - run:
          name: Install pnpm package manager
          command: |
            sudo corepack enable
            sudo corepack prepare pnpm@latest-8 --activate
      - checkout
      - restore_cache:
          name: Restore pnpm Package cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install Dependencies
          command: pnpm install
      - run:
          name: "Lint monorepo"
          command: pnpm lint

  build:
    docker:
      - image: cimg/node:20.7
    steps:
      - checkout
      - run:
          name: Install pnpm package manager
          command: |
            sudo corepack enable
            sudo corepack prepare pnpm@latest-8 --activate
      - restore_cache:
          name: Restore pnpm Package cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install Dependencies
          command: pnpm install
      - run:
          name: Build monorepo
          command: pnpm build
      - save_cache:
          name: Save build cache
          key: build-cache-{{ checksum "pnpm-lock.yaml" }}
          paths: ["!./node_modules", "!.next/cache/**"]

  test:
    docker:
      - image: cimg/node:20.7
    steps:
      - checkout
      - run:
          name: Install pnpm package manager
          command: |
            sudo corepack enable
            sudo corepack prepare pnpm@latest-8 --activate
      - restore_cache:
          name: Restore pnpm Package cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install Dependencies
          command: pnpm install
      - run:
          name: Test monorepo
          command: pnpm test

  test-e2e:
    docker:
      - image: cimg/node:20.7
    steps:
      - checkout
      - run:
          name: Install pnpm package manager
          command: |
            sudo corepack enable
            sudo corepack prepare pnpm@latest-8 --activate
      - restore_cache:
          name: Restore pnpm Package cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install Dependencies
          command: pnpm install
      - run:
          name: Test monorepo
          command: pnpm exec turbo test:e2e

  deploy:
    docker:
      - image: cimg/node:20.7
    steps:
      - checkout
      - run: echo "Deployment feature sooner!"
      # - run:
      #     name: Install pnpm package manager
      #     command: |
      #       sudo corepack enable
      #       sudo corepack prepare pnpm@latest-8 --activate
      # - restore_cache:
      #     name: Restore pnpm Package cache
      #     key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      # - run:
      #     name: Install Dependencies
      #     command: pnpm install
      # - run:
      #     name: Deploy monorepo
      #     command: pnpm deploy

workflows:
  lint-test-build:
    jobs:
      - lint
      - test
      - test-e2e
      - build
  deploy-to-production:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
