apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-poc-deploy
  namespace: devops-poc
  labels:
    app: devops-poc-app
  annotations:
spec:
  selector:
    matchLabels:
      app: devops-poc-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: devops-poc-app
    spec:
      containers:
      - name: devops-poc-web
        image: ffalanges/mono-web:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        # volumeMounts:
        # - name: config-volume
        #   mountPath: /configs/
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      - name: devops-poc-docs
        image: ffalanges/mono-docs:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        # volumeMounts:
        # - name: config-volume
        #   mountPath: /configs/
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      # volumes:
      # - name: config-volume
      #   configMap:
      #     name: devops-config